### ISSUE TITLE
0.14.3 still depends on react 0.14.2

### ISSUE THREAD

**Issue by petejkim** [jgebhardt/react-for-atom#5]
I think you mistakenly bumped version twice in
17bbd535d59dd8c439d4316da34fd4f039cb8435
and
f5da139990d810cab2dc0f178160f4cc0a35f019

**Comment by jgebhardt** [comment]
I had to re-bump it because the npm release for 17bbd53 pointed to the wrong commit, and there is no `undo` for npm. For practical purposes, just use `react-for-atom@0.14.3`, even if it delegates to `react@0.14.2` under the hood. In retrospect, it was not a good idea to try and mirror the version of a dependency.

**Comment by petejkim** [comment]
I am trying to use react 0.14.3, but with react-for-atom 0.14.3 depending on 0.14.2, npm ends up pulling in two different versions of react.
